sudo: false

cache:
  directories:
    - $HOME/.stack/

before_install:
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.0.4.3/stack-1.0.4.3-linux-x86_64.tar.gz | tar -xvz
 - mv stack-1.0.4.3-linux-x86_64/stack ~/.local/bin
 - export PATH=~/.local/bin:$PATH
 - stack --version
 - stack setup

install:
 - stack install --only-dependencies --no-terminal

script:
 - stack test :regression --coverage --no-terminal --ghc-options -Werror

after_script:
 - curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.3.0/shc-linux-x64-7.10.2.tar.bz2 | tar -xvj
 - ./shc ether regression

addons:
  apt:
    packages:
    - libgmp-dev
