language: nix

env:
  - HC=ghc822
  - HC=ghc844
  - HC=ghc861

script:
  - travis_retry ./nix-cabal new-update
  - ./nix-cabal new-test ether:regression
  - ./nix-cabal new-bench ether:bench

cache:
  directories:
    - ~/.cabal
    - ~/.ghc
